### PR TITLE
Fixing default env build so `dist/` files are production based

### PR DESCRIPTION
**Pull request by stulees**
- gulp file updated to change `dev` to `prod` for `env` value
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I don't think we need a version bump, do we? That way I can just rebuild from CCI.

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep I think we might need to version bump since we now are pulling from a version of this component. I've removed the version bump though so lets try without it first.

**Comment by donnapep** [comment]
@stulees Looks like you're right.

**Pull request merged**
