### PR TITLE
Remove unnecessary CONFIG var

### PR DESCRIPTION
**Pull request by stulees**
- Updated all config files to remove the CONFIG var creation as this component is Angular

### CODE REVIEW

**Comment by stulees** [comment]
@alex-deaconu Please review, thanks

**Comment by alex-deaconu** [comment]
@stulees looks good. However, one thing to note which I also noticed in the financial-selector is that the dist/storage-selector.js defaults to the `test` config, which means that everywhere you use the component you will be accessing the test version of the Storage dialog, rather than production. I'm not sure what the best way to resolve this is, for the financial-selector I defaulted all configs to production to prevent this; and it makes configs for components kinda useless. Thanks.

**Comment by stulees** [comment]
@alex-deaconu Ah, you're right, it does. Which is not good for this component as I need to open the appropriate location of storage-modal.html based on the environment so that the subscription status component in storage-modal.html finds the correct company. 

I'm not sure a way to resolve this either. I guess I have to change all the values to the prod value here as well and just make it aware to people that, when testing in rva-test, the subscription status will show company not found.

**Comment by stulees** [comment]
@ByronDarlison FYI my last comment above. The fix I did yesterday to ensure company is found from the subscription status in the storage modal (Video Widget settings review) is going to have to be undone. I need to force the production location of opening storage-modal.html for selecting a file. This will mean in rva-test, it will display "Company Not Found". But I can ensure this won't be the case in rva (production).

**Comment by stulees** [comment]
@ByronDarlison Somewhat disregard what I just said. Possibly a workaround can be done. Thanks

**Comment by stulees** [comment]
@alex-deaconu FYI, just changed all values of `STORAGE_MODAL` in the config files to be the production value. Will look into the workaround we discussed within the widget itself. Thanks

**Comment by alex-deaconu** [comment]
:+1:

**Pull request merged**
