### PR TITLE
Update URL for Storage Iframe - Apps

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 . Thanks!

**Comment by stulees** [comment]
@ezequielc Can you bump the version to `2.0.0`, cheers

**Comment by ezequielc** [comment]
@stulees Updated. Thanks for the reminder!

**Comment by stulees** [comment]
@ezequielc Thanks! :+1:

**Pull request merged**
