### PR TITLE
New UX and adding support for a label and selected state

### PR DESCRIPTION
**Pull request by stulees**
- Optional `label` and `selected` attributes added
- Directive now emits "picked" with the `scope.type` value along with the files
- e2e tests added and revised
- Feature version bump

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi @donnapep Please review, thanks.

**Comment by rodrigopavezi** [comment]
@stulees I was wondering, shouldn't the selected attribute be set to true when the button is clicked? cheers

**Comment by stulees** [comment]
@rodrigopavezi I chose not to do that and to put the responsibility of visual state on the parent using the component. For example, when the component is used without a label, the component won't alter its visual state internally on its button click in case this particular instance of the component doesn't require a selected state.

**Comment by rodrigopavezi** [comment]
@stulees understood but I am still confused. How do you envision this behavior? How the parent of the storage selector will know when its buttons was clicked and the selected state must be changed? cheers

**Comment by stulees** [comment]
@rodrigopavezi When the button is clicked it will launch the modal. When file(s) are selected and the modal closes, the component emits "picked" which I've now added the selector type in the event. So, on the parents handler for "picked" event, it can set the `selected` state on its appropriate instance of storage-selector based on the value of `type` provided in the event. See here - https://github.com/Rise-Vision/component-storage-selector/blob/feature/label-selected/src/dtv-storage-selector.js#L52

**Comment by rodrigopavezi** [comment]
@stulees got it. Thanks a mill for the clarification. :+1:

**Comment by stulees** [comment]
@rodrigopavezi Do you think it's better if the component manages its state internally only? I did it this way to provide more flexibility, but I'm open to changing this if we think it's going to add more complexity outside the component.

**Comment by rodrigopavezi** [comment]
@stulees I think this way is the right one as we have the possibility to have 2 storage selectors, one for single and another for folder. So, the parent can control when one is selected and deselect the other. I don't think this can be achieved from inside the component. cheers

**Comment by stulees** [comment]
@rodrigopavezi Okay agreed, thanks!

**Pull request merged**
